Add account management category
MetaMask/snaps-directory pull request #164
Opened 2023-10-11 09:06 UTC by Mrtenz

2023-10-11 09:21 UTC, Mrtenz commented on src/features/filter/store.test.ts
> +      const state = Object.values(RegistrySnapCategory).reduce(
I refactored this slightly, so the test doesn't break if we add a new category.

2024-01-17 13:11 UTC, FrederikBolding commented on src/constants.ts
> +    header: defineMessage`Manage Your Accounts`,
I think this is still TBD

2024-01-17 13:19 UTC, FrederikBolding requested changes

2024-01-17 13:19 UTC, FrederikBolding commented on src/features/snap/components/Data.tsx
> +          <WarningIcon width="20px" fill="warning.default" />
`warning.default` is more orange in light mode. Is that intentional?

![image](https://github.com/MetaMask/snaps-directory/assets/1561200/565f0829-c644-442f-bfa6-6d40955faa89)

cc @eriknson

2024-01-17 13:19 UTC, FrederikBolding commented on src/components/icons/add-user.svg
This icon looks broken

2024-01-17 13:19 UTC, FrederikBolding commented on src/components/FooterAccountManagementTerms.tsx
> +export const FooterAccountManagementTerms: FunctionComponent = () => (
Confirm whether we also need to show the existing terms at the bottom. We may need to

2024-01-17 13:20 UTC, Mrtenz commented on src/components/FooterAccountManagementTerms.tsx
> +export const FooterAccountManagementTerms: FunctionComponent = () => (
This includes the existing terms.

2024-01-17 13:21 UTC, Mrtenz commented on src/features/snap/components/Data.tsx
> +          <WarningIcon width="20px" fill="warning.default" />
Yeah, this is the DS warning color.

2024-01-17 13:21 UTC, Mrtenz commented on src/constants.ts
> +    header: defineMessage`Manage Your Accounts`,
Yep. I just put something there for now.

2024-01-17 13:28 UTC, FrederikBolding commented on src/components/FooterAccountManagementTerms.tsx
> +export const FooterAccountManagementTerms: FunctionComponent = () => (
yes nvm I'm blind

2024-01-17 13:28 UTC, FrederikBolding commented on src/components/FooterAccountManagementTerms.tsx
> +export const FooterAccountManagementTerms: FunctionComponent = () => (
Somehow I missed that 😓

2024-01-17 16:35 UTC, FrederikBolding submitted a review, later dismissed

2024-01-25 13:02 UTC, FrederikBolding commented on src/pages/snap/{Snap.location}/{Snap.slug}.tsx
> +        keyRecovery
We should probably support `additionalSourceCode` in this PR too

2024-02-07 13:17 UTC, FrederikBolding submitted a review, later dismissed

2024-02-13 12:48 UTC, FrederikBolding approved these changes

2024-02-13 12:48 UTC, merged