Use `wallet_getAllSnaps` and revoke permissions post-install
MetaMask/snaps-directory pull request #388
Opened 2024-04-25 18:46 UTC by hmalik88

Swapping out `wallet_getSnaps` for `wallet_getAllSnaps` so that the directory doesn't need permission to get a list of the currently installed snaps. `wallet_revokePermissions` is invoked to remove the directory's `wallet_snap` permission on every install.

2024-04-26 10:32 UTC, Mrtenz reviewed
Looks good to me. Just wondering if we can assume that `wallet_getAllSnaps` is available, since we introduced it quite recently?

2024-04-26 15:12 UTC, hmalik88 commented
> Looks good to me. Just wondering if we can assume that `wallet_getAllSnaps` is available, since we introduced it quite recently?

I suppose we can hold off on merging this PR until we know it has made its way to stable.

2024-04-29 08:02 UTC, FrederikBolding commented
@Mrtenz The RPC method was introduced in extension `11.9`. Seems safe enough to start using?

2024-04-29 13:59 UTC, Mrtenz requested changes
Looks like this is not in stable?
<img width="596" alt="image" src="https://github.com/MetaMask/snaps-directory/assets/7503723/a8e08c90-f84a-4e68-be9e-eb22e700e827">

2024-04-29 14:23 UTC, Mrtenz approved these changes

2024-04-29 14:26 UTC, merged